name: ci

on:
  pull_request:
    branches:
      - main
  pull_request_target:
    types:
      - labeled

jobs:
  fmt:
    if: |
      (github.event_name == 'pull_request' && ! github.event.pull_request.head.repo.fork && github.event.pull_request.user.login != 'dependabot[bot]' && ! contains(github.event.pull_request.labels.*.name, 'safe-to-test')) ||
      (github.event_name == 'pull_request_target' && contains(github.event.pull_request.labels.*.name, 'safe-to-test'))
    uses: signoz/primus.workflows/.github/workflows/go-fmt.yaml@main
    secrets: inherit
    with:
      PRIMUS_REF: main
      GO_VERSION: 1.25
  lint:
    if: |
      (github.event_name == 'pull_request' && ! github.event.pull_request.head.repo.fork && github.event.pull_request.user.login != 'dependabot[bot]' && ! contains(github.event.pull_request.labels.*.name, 'safe-to-test')) ||
      (github.event_name == 'pull_request_target' && contains(github.event.pull_request.labels.*.name, 'safe-to-test'))
    uses: signoz/primus.workflows/.github/workflows/go-lint.yaml@main
    secrets: inherit
    with:
      PRIMUS_REF: main
      GO_VERSION: 1.25
  test:
    if: |
      (github.event_name == 'pull_request' && ! github.event.pull_request.head.repo.fork && github.event.pull_request.user.login != 'dependabot[bot]' && ! contains(github.event.pull_request.labels.*.name, 'safe-to-test')) ||
      (github.event_name == 'pull_request_target' && contains(github.event.pull_request.labels.*.name, 'safe-to-test'))
    uses: signoz/primus.workflows/.github/workflows/go-test.yaml@main
    secrets: inherit
    with:
      PRIMUS_REF: main
      GO_TEST_CONTEXT: ./...
      GO_VERSION: 1.25
  deps:
    if: |
      (github.event_name == 'pull_request' && ! github.event.pull_request.head.repo.fork && github.event.pull_request.user.login != 'dependabot[bot]' && ! contains(github.event.pull_request.labels.*.name, 'safe-to-test')) ||
      (github.event_name == 'pull_request_target' && contains(github.event.pull_request.labels.*.name, 'safe-to-test'))
    uses: signoz/primus.workflows/.github/workflows/go-deps.yaml@main
    secrets: inherit
    with:
      PRIMUS_REF: main
      GO_VERSION: 1.25
  examples:
    if: |
      (github.event_name == 'pull_request' && ! github.event.pull_request.head.repo.fork && github.event.pull_request.user.login != 'dependabot[bot]' && ! contains(github.event.pull_request.labels.*.name, 'safe-to-test')) ||
      (github.event_name == 'pull_request_target' && contains(github.event.pull_request.labels.*.name, 'safe-to-test'))
    runs-on: ubuntu-latest
    steps:
      - name: self-checkout
        uses: actions/checkout@v4
      - name: go-install
        uses: actions/setup-go@v5
        with:
          go-version: "1.25"
      - name: gen-examples
        run: |
          make gen-examples
          git diff --compact-summary --exit-code || (echo; echo "Unexpected difference in docs/examples/. Run 'make gen-examples' locally and commit."; exit 1)
  schemas:
    if: |
      (github.event_name == 'pull_request' && ! github.event.pull_request.head.repo.fork && github.event.pull_request.user.login != 'dependabot[bot]' && ! contains(github.event.pull_request.labels.*.name, 'safe-to-test')) ||
      (github.event_name == 'pull_request_target' && contains(github.event.pull_request.labels.*.name, 'safe-to-test'))
    runs-on: ubuntu-latest
    steps:
      - name: self-checkout
        uses: actions/checkout@v4
      - name: go-install
        uses: actions/setup-go@v5
        with:
          go-version: "1.25"
      - name: gen-schemas
        run: |
          make gen-schemas
          git diff --compact-summary --exit-code || (echo; echo "Unexpected difference in docs/schemas/ directory. Run 'make gen-schemas' locally and commit."; exit 1)
  docs:
    if: |
      (github.event_name == 'pull_request' && ! github.event.pull_request.head.repo.fork && github.event.pull_request.user.login != 'dependabot[bot]' && ! contains(github.event.pull_request.labels.*.name, 'safe-to-test')) ||
      (github.event_name == 'pull_request_target' && contains(github.event.pull_request.labels.*.name, 'safe-to-test'))
    runs-on: ubuntu-latest
    steps:
      - name: self-checkout
        uses: actions/checkout@v4
      - name: go-install
        uses: actions/setup-go@v5
        with:
          go-version: "1.25"
      - name: gen-docs
        run: |
          make gen-docs
          git diff --compact-summary --exit-code || (echo; echo "Unexpected difference in README.md. Run 'make gen-docs' locally and commit."; exit 1)
